# Generated by Django 6.0.1 on 2026-01-19 10:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami formati: '+998901234567'. 9-15 ta raqam.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqam')),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='Til')),
                ('default_currency', models.CharField(choices=[('UZS', 'UZS (Soʻm)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('RUB', 'RUB (₽)')], default='UZS', max_length=3, verbose_name='Asosiy valyuta')),
                ('timezone', models.CharField(choices=[('Asia/Tashkent', 'Asia/Tashkent (Uzbekistan)'), ('Europe/Moscow', 'Europe/Moscow (Russia)'), ('America/New_York', 'America/New_York (USA)'), ('Europe/London', 'Europe/London (UK)')], default='Asia/Tashkent', max_length=50, verbose_name='Vaqt mintaqasi')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Davlat')),
                ('email_verified', models.BooleanField(db_index=True, default=False, verbose_name='Email tasdiqlangan')),
                ('phone_verified', models.BooleanField(db_index=True, default=False, verbose_name='Telefon tasdiqlangan')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email xabarnomalar')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push xabarnomalar')),
                ('marketing_emails', models.BooleanField(default=False, verbose_name='Marketing email lari')),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True, verbose_name='Tug‘ilgan sana')),
                ('profile_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_images/%Y/%m/%d/', verbose_name='Profil rasmi')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Oxirgi faollik')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Oxirgi login IP')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Loginlar soni')),
                ('is_premium', models.BooleanField(db_index=True, default=False, verbose_name='Premium foydalanuvchi')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Premium muddati')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Ikki faktorli autentifikatsiya')),
                ('profile_completed', models.BooleanField(db_index=True, default=False, verbose_name='Profil to‘ldirilgan')),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Yaratilgan IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Muddati')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Ishlatilgan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Email tasdiqlash',
                'verbose_name_plural': 'Email tasdiqlashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('locked', 'Bloklangan')], db_index=True, default='success', max_length=10, verbose_name='Holat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokatsiya')),
                ('device', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qurilma')),
                ('browser', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brauzer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Login tarixi',
                'verbose_name_plural': 'Login tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Muddati')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Ishlatilgan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Parol tiklash tokeni',
                'verbose_name_plural': 'Parol tiklash tokenlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='idx_user_phone'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'email_verified'], name='idx_user_active'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='idx_user_date_joined'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token', 'is_used'], name='idx_email_verify_token'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'is_used'], name='idx_email_verify_user'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='idx_email_verify_expires'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'status'], name='idx_login_history_user'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='idx_login_history_ip'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['created_at', 'status'], name='idx_login_history_date'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token', 'is_used'], name='idx_pwd_reset_token'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'is_used'], name='idx_pwd_reset_user'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='idx_pwd_reset_expires'),
        ),
    ]
