# Generated by Django 6.0.1 on 2026-01-21 11:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(default='fas fa-shopping-cart', max_length=50, verbose_name='Ikon')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Rang')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiqim kategoriyasi',
                'verbose_name_plural': 'Chiqim kategoriyalari',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('color', models.CharField(default='#6b7280', max_length=20, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiqim tegi',
                'verbose_name_plural': 'Chiqim teglari',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Byudjet miqdori')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('period', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], default='monthly', max_length=20, verbose_name='Davr')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('alert_threshold', models.IntegerField(default=80, verbose_name='Ogohlantirish chegirasi (%)')),
                ('send_alerts', models.BooleanField(default=True, verbose_name='Ogohlantirish yuborish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expenses.expensecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Byudjet',
                'verbose_name_plural': 'Byudjetlar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'category', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Valyuta kursi')),
                ('amount_in_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Summa (UZS)')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Bank kartasi'), ('transfer', "O'tkazma"), ('online', "Onlayn to'lov"), ('other', 'Boshqa')], default='cash', max_length=50, verbose_name="To'lov usuli")),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Chek rasmi')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Takrorlanuvchi')),
                ('recurrence_interval', models.CharField(blank=True, choices=[('daily', 'Har kuni'), ('weekly', 'Har hafta'), ('monthly', 'Har oy'), ('yearly', 'Har yil')], max_length=20, verbose_name="Takrorlanish oralig'i")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('needs_review', models.BooleanField(default=False, verbose_name="Ko'rib chiqish kerak")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory', verbose_name='Kategoriya')),
                ('tags', models.ManyToManyField(blank=True, to='expenses.expensetag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'), models.Index(fields=['user', 'category'], name='expenses_ex_user_id_45749f_idx'), models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx'), models.Index(fields=['currency'], name='expenses_ex_currenc_f13b94_idx')],
            },
        ),
    ]
