# Generated by Django 6.0.1 on 2026-01-19 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecurrencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Har kuni'), ('weekly', 'Har hafta'), ('biweekly', 'Har ikki haftada'), ('monthly', 'Har oy'), ('quarterly', 'Har chorakda'), ('yearly', 'Har yil'), ('custom', 'Maxsus')], max_length=20, verbose_name='Takrorlanish turi')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Interval')),
                ('week_days', models.JSONField(blank=True, help_text='JSON formatida: [1,3,5] (1-Dushanba, 7-Yakshanba)', null=True, verbose_name='Hafta kunlari')),
                ('month_days', models.JSONField(blank=True, help_text='JSON formatida: [1,15,31]', null=True, verbose_name='Oy kunlari')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal takrorlanishlar')),
            ],
            options={
                'verbose_name': 'Takrorlanish patterni',
                'verbose_name_plural': 'Takrorlanish patternlari',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(default='fas fa-money-bill-wave', max_length=50, verbose_name='Ikonka')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Rang')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart kategoriya')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim kategoriyasi',
                'verbose_name_plural': 'Kirim kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('goal_type', models.CharField(choices=[('monthly', 'Oylik'), ('yearly', 'Yillik'), ('custom', 'Maxsus')], default='monthly', max_length=20, verbose_name='Maqsad turi')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Maqsad miqdori')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('EUR', 'Euro'), ('RUB', 'Rubl'), ('CNY', 'Yuan')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='Bildirishnomalar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='goals', to='income.incomecategory', verbose_name='Kategoriyalar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim maqsadi',
                'verbose_name_plural': 'Kirim maqsadlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim manbasi',
                'verbose_name_plural': 'Kirim manbalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim tegi',
                'verbose_name_plural': 'Kirim teglari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Miqdor')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('EUR', 'Euro'), ('RUB', 'Rubl'), ('CNY', 'Yuan')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('source', models.CharField(max_length=200, verbose_name='Manba')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Bank kartasi'), ('transfer', "Bank o'tkazmasi"), ('digital', "Digital to'lov"), ('other', 'Boshqa')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('received', 'Qabul qilindi'), ('pending', 'Kutilmoqda'), ('cancelled', 'Bekor qilindi')], default='received', max_length=20, verbose_name='Holat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('attachment', models.FileField(blank=True, help_text='Chek, shartnoma yoki boshqa hujjat', null=True, upload_to='income_attachments/%Y/%m/', verbose_name='Fayl')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Takrorlanuvchi')),
                ('recurrence_pattern', models.JSONField(blank=True, help_text='JSON formatida: {"type": "monthly", "interval": 1, "end_date": "2024-12-31"}', null=True, verbose_name='Takrorlanish qoidasi')),
                ('next_occurrence', models.DateField(blank=True, null=True, verbose_name='Keyingi takrorlanish')),
                ('is_transfer', models.BooleanField(default=False, verbose_name="Hisoblar orasidagi o'tkazma")),
                ('is_taxable', models.BooleanField(default=False, verbose_name='Soliqqa tortiladigan')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Soliq miqdori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='income.incomecategory', verbose_name='Kategoriya')),
                ('source_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='income.incomesource', verbose_name='Manba obyekti')),
                ('tags', models.ManyToManyField(blank=True, related_name='incomes', to='income.incometag')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-date', '-created_at'],
                'permissions': [('export_income', 'Kirimlarni export qilish'), ('view_statistics', "Statistikalarni ko'rish")],
            },
        ),
        migrations.CreateModel(
            name='IncomeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Miqdor')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('EUR', 'Euro'), ('RUB', 'Rubl'), ('CNY', 'Yuan')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('source', models.CharField(max_length=200, verbose_name='Manba')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Bank kartasi'), ('transfer', "Bank o'tkazmasi"), ('digital', "Digital to'lov"), ('other', 'Boshqa')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='income.incomecategory', verbose_name='Kategoriya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim shabloni',
                'verbose_name_plural': 'Kirim shablonlari',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['user', 'is_default'], name='income_inco_user_id_4bc23c_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['user', 'created_at'], name='income_inco_user_id_3e6448_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='incomegoal',
            index=models.Index(fields=['user', 'status'], name='income_inco_user_id_e9d17a_idx'),
        ),
        migrations.AddIndex(
            model_name='incomegoal',
            index=models.Index(fields=['user', 'start_date'], name='income_inco_user_id_2efb20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomesource',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='incometag',
            index=models.Index(fields=['user', 'name'], name='income_inco_user_id_4ff586_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incometag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='income_inco_user_id_f74de7_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'category'], name='income_inco_user_id_04ffe9_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'status'], name='income_inco_user_id_114a47_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'is_recurring'], name='income_inco_user_id_327894_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'payment_method'], name='income_inco_user_id_d95901_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'source'], name='income_inco_user_id_d9f5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['created_at'], name='income_inco_created_425312_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incometemplate',
            unique_together={('user', 'name')},
        ),
    ]
